# Generated by Django 3.1.2 on 2020-12-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Аккаунты', 'verbose_name_plural': 'Аккаунты'},
        ),
    ]
